name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release_binary:
    name: Release Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  release_image:
    name: Release Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/blackjack-simulator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/blackjack-simulator:${{ steps.get_version.outputs.major }}
            ${{ secrets.DOCKERHUB_USERNAME }}/blackjack-simulator:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
            ${{ secrets.DOCKERHUB_USERNAME }}/blackjack-simulator:${{ steps.get_version.outputs.version-without-v }}